### ISSUE TITLE
How to do post-smoothing using equipercentile method with frequency table?

### ISSUE THREAD

**Issue by seonghobae** [talbano/equate#1]
Hello,

I can do pre-smoothing using equipercentile method with frequency table like this;

``` R
# pre-smoothing 2009B=Eq(2009A) and 2009C=Eq(2009A)
  # pre-smoothing (equipercentile post-smoothing is not available now in R)
    mod_req4_pre <- equate(x = freqtab(mh2009$b), y = freqtab(mh2009$a), type = 'equipercentile', method = 'none', smoothmethod = 'loglinear')
    plot(mod_req4_pre)

    mod_req5_pre <- equate(x = freqtab(mh2009$c), y = freqtab(mh2009$a), type = 'equipercentile', method = 'none', smoothmethod = 'loglinear')
    plot(mod_req5_pre)
```

But, I do not know how to do post-smoothing using the equipercentile method. Please let me know how to that works.

Best wishes,
Seongho Bae

**Comment by talbano** [comment]
Postsmoothing isn't currently supported in the equate package. You'd have to do this manually in R using something like the splinefun function.
