### ISSUE TITLE
Inaccurate concordance value in equipercentile method

### ISSUE THREAD

**Issue by seonghobae** [talbano/equate#2]
Hi,

I found sometimes equate() calculates inaccurate concordance value in equipercentile method when a score has a few frequency; extremely low scores whose percents are less than .5% (.005).

I attached my handouts in my class...
![image](https://cloud.githubusercontent.com/assets/8172694/13964702/613ae354-f0ae-11e5-9619-b5e5db00ac56.png)

Best wishes,
Seongho

**Comment by talbano** [comment]
Can you post code from a reproducible example of the error?
