### ISSUE TITLE
Problem with legend in plot.equate

### ISSUE THREAD

**Issue by cliuhan** [talbano/equate#3]
When plotting the equating function from a single-group equating, the legend is off.

``` R
m36 <- freqtab(PISA$totals$b6[1:198, c("r3a", "r6")], scales = list(0:15, 0:16))
plot(equate(m36, type = "equip"))
```

**Comment by talbano** [comment]
equate 2.0-4 includes a `design` argument under `freqtab()` where you specify the equating study design. If you leave it off, it defaults to nonequivalent groups, and then the plot defaults to nominal weights (hence NW) as the method.
To keep the legend straight, you'd have to specify a single group design.

``` R
# install.packages("equate")
library("equate")
m36r <- freqtab(PISA$totals$b6[1:198, c("r3a", "r6")], scales = list(0:15, 0:16),
  design = "sg")
plot(equate(m36r, type = "equip"))
```
