### ISSUE TITLE
Equate doesn't work with do.call if freqtab

### ISSUE THREAD

**Issue by swnydick** [talbano/equate#4]
Trying to use the `equate::equate` function with freqtab input. Due to

```
xname <- ifelse(exists(deparse(substitute(x)), 1,
 			inherits = FALSE), deparse(substitute(x)), "x")
```
when I run `do.call(what, args)` to make it easier to automate/update arguments to the function, I get the error

```
Error in exists(deparse(substitute(x)), 1, inherits = FALSE) : 
  first argument has length > 1
```

In general, R functions should work by setting up a call explicitly (e.g., `f(stuff)`) as well as by setting up the calls separately and evaluating them (e.g., `do.call(what, args)` or `eval(as.call(c(list(f, args))))`.

Reprex:

``` r
library(equate)

set.seed(888)
x <- freqtab(x      = sample(50, 5, replace = TRUE),
             scales = 1:5)

# works
equate::equate(x = x,
               y = x)
#> 
#> Identity Equating: x to x 
#> 
#> Design: equivalent groups 
#> 
#> Summary Statistics:
#>    mean  sd skew kurt min max n
#> x     1 NaN  NaN  NaN   1   1 1
#> y     1 NaN  NaN  NaN   1   1 1
#> yx    1 NaN  NaN  NaN   1   1 1
#> 
#> Coefficients:
#> intercept     slope        cx        cy        sx        sy 
#>         0         1         3         3         4         4

# doesn't work
args <- list(x = x,
             y = x)

do.call(what = equate::equate,
        args = args)
#> Error in exists(deparse(substitute(x)), 1, inherits = FALSE): first argument has length > 1
```

<sup>Created on 2022-07-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The `equate:::equate.list` clearly uses `do.call`, so I'm wondering why does it not apply here. Also I do understand you can use the `equate:::equate.list` to accomplish the same goal (which is what I resorted to), but it's a bit odd that you need a work-around to make this work with `do.call`.

**Comment by jmbarbone** [comment]
Culprit likely seems to be `deparse` which can return a vector with length > 1.  Solution would be replacing with `deparse1` or a wrapping calls in `paste(., collapse)`

``` r
deparse(letters)
#> [1] "c(\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\", \"i\", \"j\", \"k\", \"l\", "     
#> [2] "\"m\", \"n\", \"o\", \"p\", \"q\", \"r\", \"s\", \"t\", \"u\", \"v\", \"w\", \"x\", \"y\", "
#> [3] "\"z\")"
deparse1
#> function (expr, collapse = " ", width.cutoff = 500L, ...) 
#> paste(deparse(expr, width.cutoff, ...), collapse = collapse)
#> <bytecode: 0x0000028351655070>
#> <environment: namespace:base>
deparse1(letters)
#> [1] "c(\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\", \"i\", \"j\", \"k\", \"l\", \"m\", \"n\", \"o\", \"p\", \"q\", \"r\", \"s\", \"t\", \"u\", \"v\", \"w\", \"x\", \"y\", \"z\")"
paste(deparse(letters), collapse = " ")
#> [1] "c(\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\", \"i\", \"j\", \"k\", \"l\",  \"m\", \"n\", \"o\", \"p\", \"q\", \"r\", \"s\", \"t\", \"u\", \"v\", \"w\", \"x\", \"y\",  \"z\")"
```

<sup>Created on 2022-08-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by talbano** [comment]
Thanks @swnydick and @jmbarbone for figuring this out. The latest commit now uses deparse1.
