### ISSUE TITLE
Square root missing for analytical SEs in linear equating?

### ISSUE THREAD

**Issue by TomBentonCA** [talbano/equate#5]
I've noticed that the analytical standard errors produced by the equate function with linear equating are almost  exactly the squares  of the standard errors produced by bootstrapping. I suspect that a square root has been missed somewhere in the analytical calculation.

Example showing the issue is below.

> rx <- as.freqtab(ACTmath[, 1:2])
> ry <- as.freqtab(ACTmath[, c(1, 3)])
> set.seed(2007)
> req3 <- equate(rx, ry, type = "l", boot = TRUE, reps = 500)
> 
> summary(req3$concordance$se)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.03363 0.03797 0.05084 0.06188 0.07225 0.14069 
> summary(req3$concordance$se.b)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1802  0.1920  0.2232  0.2426  0.2753  0.3838 
> summary(sqrt(req3$concordance$se))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1834  0.1948  0.2255  0.2426  0.2688  0.3751 
> 
> #SE of difference in means (as a sense check on rough expected scale of SE)
> x=rep(ACTmath$scale,ACTmath$xcount)
> y=rep(ACTmath$scale,ACTmath$ycount)
> sqrt(var(x)/length(x)+var(y)/length(y))
[1] 0.1866315
> 
>

**Comment by talbano** [comment]
You're right, an internal function was missing sqrt. Thanks for sharing. Just pushed an update in commit 4ca8b12.
